Put related functions next to each other

diff --git a/git-hooks b/git-hooks
--- a/git-hooks
+++ b/git-hooks
@@ -57,6 +57,30 @@ function list_hooks_in_dir
     fi
 }
 
+function list_hooks
+{
+    GITDIR=`git rev-parse --git-dir`
+    cat "${GITDIR}/hooks/pre-commit" 2> /dev/null | grep 'git-hooks' > /dev/null 2> /dev/null
+    if [ $? = 0 ] ; then
+        echo "Git hooks ARE installed in this repository."
+        echo ""
+    else
+        echo "Git hooks are NOT installed in this repository. (Run 'git hooks --install' to install it)"
+        echo ""
+    fi
+
+    echo 'Listing User, Project, and Global hooks:'
+    echo '---'
+    for dir in `hook_dirs`; do
+        echo "${dir}:"
+        for hook in `list_hooks_in_dir "${dir}" 2` ; do
+            echo -n `basename \`dirname "${hook}"\``
+            echo -e "/`basename "${hook}"` \t- `${hook} --about`"
+        done
+        echo ""
+    done
+}
+
 function run_hooks
 {
     dir="${1}"
@@ -138,35 +162,6 @@ git-hooks run "$0" "$@"';
     fi
 }
 
-function list_hooks
-{
-    GITDIR=`git rev-parse --git-dir`
-    cat "${GITDIR}/hooks/pre-commit" 2> /dev/null | grep 'git-hooks' > /dev/null 2> /dev/null
-    if [ $? = 0 ] ; then
-        echo "Git hooks ARE installed in this repository."
-        echo ""
-    else
-        echo "Git hooks are NOT installed in this repository. (Run 'git hooks --install' to install it)"
-        echo ""
-    fi
-
-    echo 'Listing User, Project, and Global hooks:'
-    echo '---'
-    for dir in `hook_dirs`; do
-        echo "${dir}:"
-        for hook in `list_hooks_in_dir "${dir}" 2` ; do
-            echo -n `basename \`dirname "${hook}"\``
-            echo -e "/`basename "${hook}"` \t- `${hook} --about`"
-        done
-        echo ""
-    done
-}
-
-function report_error {
-    echo "Hook failed: $last_run_hook"
-    exit 1
-}
-
 function installglobal {
     TEMPLATE="$HOME/.git-template-with-git-hooks"
     if [ ! -d "${TEMPLATE}" ] ; then
@@ -187,6 +182,11 @@ echo \"git hooks not installed in this repository.  Run 'git hooks --install' to
 
 function uninstallglobal {
     git config --global --unset init.templatedir
+}
+
+function report_error {
+    echo "Hook failed: $last_run_hook"
+    exit 1
 }
 
 case $1 in
