Augmenting the copyright_year check to be able to check that a copyright exists for a specific entitfy for the current year.

diff --git a/contrib/pre-commit/copyright_year b/contrib/pre-commit/copyright_year
--- a/contrib/pre-commit/copyright_year
+++ b/contrib/pre-commit/copyright_year
@@ -1,6 +1,7 @@
 #!/bin/bash
 #
 # Copyright (c) 2010, Benjamin C. Meyer <ben@meyerhome.net>
+# Copyright (c) 2013, Phil Black-Knight <pblack88@gmail.com>
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -31,17 +32,31 @@ function test_file {
     if grep 'Copyright ' "${file}" | grep -v grep >/dev/null
     then
         year=`date +%Y`
-        grep 'Copyright ' "${file}" | grep "${year}" >/dev/null
-        if [ $? -ne 0 ] ; then
-            echo "Error: $file seems to be missing a copyright string with the year $year in it.";
-            exit 1
+        cr_holder=`git config --get hooks.copyrightholder`
+        if [ -n "${cr_holder}" ]
+        then
+            grep 'Copyright ' "${file}" | grep "${year}" | grep "${cr_holder}" >/dev/null
+            if [ $? -ne 0 ] ; then
+                echo "Error: $file seems to be missing a copyright string for ${cr_holder} with the year $year in it.";
+                exit 1
+            fi
+        else
+            grep 'Copyright ' "${file}" | grep "${year}" >/dev/null
+            if [ $? -ne 0 ] ; then
+                echo "Error: $file seems to be missing a copyright string with the year $year in it.";
+                exit 1
+            fi
         fi
     fi
 }
 
 case "${1}" in
     --about )
-        echo "Check that the files have a copyright with the current year."
+        cat << EOF
+Check that the files have a copyright with the current year.  If the git config key
+"hooks.copyrightholder" is set, the script will verify that in addition to the
+current year, a copyright notice exists for person/entity listed in "hooks.copyrightholder"
+EOF
         ;;
     * )
         for file in `git diff-index --cached --name-only HEAD` ; do
